### ISSUE TITLE
click links via mobile facebook isn't working

### ISSUE THREAD

**Issue by jackylee0424** [jackylee0424/taiwanuxd#102]
click links like http://taiwanuxd.org/?profile via mobile facebook app will not redirect login to designated page.

.authWithOAuthPopup() does not work with native facebook app, according to:
http://stackoverflow.com/questions/26369551/firebase-how-to-authenticate-user-through-native-facebook-app

**Comment by a33kuo** [comment]
Fixed in ca1e082d00d227e366b179e48d2ab3dcc44c8c67

**Comment by jackylee0424** [comment]
it's a cool one-line fix!
